### ISSUE TITLE
[TO-DO] add new gradient handler to animated tab

### ISSUE THREAD

**Issue by Oli-idk** [Oli-idk/SimplyMC#29]
- [x] fix html/css part of page

- [x] fix js part of page

- [x] fix any other bugs that may come up while doing this

**Comment by Oli-idk** [comment]
html/css parts of the page have been updated to match new hexnicks page

**Comment by Oli-idk** [comment]
js has been updated and looks good

**Comment by Oli-idk** [comment]
everything works fine
